### ISSUE TITLE
Add newline support to listing description

### ISSUE THREAD

**Issue by gpellizzari** [holdex/holdex-io#40] opened 2020-03-03 02:14 UTC
Allow listing description to go on a new line.

**Job story:**

- **When** a listing description is published
- **I want** the text to go to a new line
- **so that** the listing is easier to read for the users

 > Hey, Vadim!

Thanks a ton for the feature.

I just have a few questions.

Firstly, for the bio about ChangeHero, **_is there any way to post it in different lines instead of a paragraph_**.

Something like: 

Instant cryptocurrency exchange providing the best standard and fixed rates. 
No more hassles of signups and logins! 
Swap crypto-to-crypto or buy instantly with Credit/Debit card in a snap. 
Our support team has got your back as always.
Fast. Simple. Safe.

Secondly, for posting the comments and maintaining the account, will you be providing us access to an exclusive account or do we have to create an account like everybody and post the comments and offers?

Finally, I guess we can promote any discounts on exchange there. But, what about giveaways? Is there a possibility to promote social media activities, articles or other activities?

Looking forward to your response.

Thanks in advance.

Best,
ChangeHero Team

**Link:** [Conversation with ChangeHero](https://app.intercom.com/a/apps/d1yuld8c/respond/inbox/all/conversations/25843003259)

**Customer:** [ChangeHero](https://app.intercom.com/a/apps/d1yuld8c/users/5e4e514c0e7e46da139ea9bb/all-conversations) from [ChangeHero Exchange](https://app.intercom.com/a/apps/d1yuld8c/companies/5e5679f44478f1d4865e0900)
**Customer ID:** 7e0d48fc-f817-4509-9e08-cc2f12b5b1de
**Company ID:** 5e5679f44478f1d4865e0901-qualification-company
___
Intercom Operator will send a note to [this conversation](https://app.intercom.com/a/apps/d1yuld8c/respond/inbox/all/conversations/25843003259) when this issue is closed.

**Comment by zolotokrylin** [comment] 2020-06-10 05:58
Is duplicate of this issue https://github.com/holdex/holdex-platform-frontend/issues/1540

**Closed by zolotokrylin** 2020-06-10 05:58 UTC
